### ISSUE TITLE
Minor: `homeassitant` tag is mispelled for repo

### ISSUE THREAD

**Issue by amcfague** [8ff/firescrew#4]
`homeassitant` should be `homeassistant`. Unbelivably minor but not sure if this is used for discovery!

**Comment by amcfague** [comment]
<img width="243" alt="image" src="https://github.com/8ff/firescrew/assets/144809/b06a58d1-76b4-4dca-a98f-dcf40e36c297">

**Comment by chiefMarlin** [comment]
Good catch! Thanks
