### ISSUE TITLE
H265 will not play in Safari

### ISSUE THREAD

**Issue by wehbs** [8ff/firescrew#7]
So h265 works great in chrome but would love to view on ios. I came across this post 

https://www.reddit.com/r/ShinobiCCTV/comments/hh4ueo/howto_get_h265_playback_working_on_safari/?utm_source=share&utm_medium=ios_app&utm_name=ioscss&utm_content=2&utm_term=1

Seems like a simple solution?

**Comment by chiefMarlin** [comment]
Its worth trying it, you are suggesting that this be added to tje Onlyremuxmp4 parameters ? 
	if globalConfig.Video.OnlyRemuxMp4 {
		cmd = exec.Command("ffmpeg", "-i", inputFile, "-c", "copy", outputFile)

**Comment by wehbs** [comment]
if globalConfig.Video.OnlyRemuxMp4 {
    cmd = exec.Command("ffmpeg", "-i", inputFile, "-c", "copy", "-hls_segment_type", "fmp4", outputFile)
}

I think that should do it.

**Comment by chiefMarlin** [comment]
This has been implemented in the pre release i mentioned in the other issue

**Comment by wehbs** [comment]
Ok, so I tried it out but it still didn't work. Spent some time messing with ffmpeg and I finally got it to work. Can you please change to:

if globalConfig.Video.OnlyRemuxMp4 {
    cmd = exec.Command("ffmpeg", "-i", inputFile, 
                       "-c:v", "copy", 
                       "-c:a", "aac", 
                       "-tag:v", "hvc1", 
                       "-movflags", "+faststart", 
                       "-hls_segment_type", "fmp4", 
                       outputFile)
}

**Comment by chiefMarlin** [comment]
When i run `ffmpeg -i a.ts -c:v copy -c:a aac -tag:v hvc1 -movflags +faststart -hls_segment_type fmp4 b.mp4`
i get an error
`  Stream #0:0[0x100]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 25 fps, 50 tbr, 90k tbn
  Stream #0:1[0x101]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp, 130 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (aac (native) -> aac (native))
Press [q] to stop, [?] for help
[mp4 @ 0x12ef068a0] Tag hvc1 incompatible with output codec id '27' (avc1)
[out#0/mp4 @ 0x600000a600c0] Could not write header (incorrect codec parameters ?): Invalid data found when processing input
[aost#0:1/aac @ 0x12ef07ef0] Error initializing output stream: 
[aac @ 0x12ef081c0] Qavg: nan
Conversion failed!`

**Comment by wehbs** [comment]
Seems like maybe because -tag:v hvc1 only works on HEVC (h265)

**Comment by wehbs** [comment]
So maybe this should be another option in the config for h265 users?

**Comment by chiefMarlin** [comment]
Yup, im gonna see if i can dynamically get this info

**Comment by chiefMarlin** [comment]
So when stream info is pulled, it gets the codec name, for me it shows up as 'h264' when     "printDebug": true, is enabled in config
i am assuming for your stream it would show h265 or something similar ?
If thats the case then i can use that to determine ffmpeg options

**Comment by wehbs** [comment]
"codec_name": "hevc",
"codec_long_name": "H.265 / HEVC (High Efficiency Video Coding)",

**Comment by chiefMarlin** [comment]
Thanks,
You can try it here
https://github.com/8ff/firescrew/releases/download/onnx_test_release/firescrew.darwin.arm64

**Comment by wehbs** [comment]
Ok, so it's improved, in that it allows me to press play and plays the audio but still no video in Safari. However, if I open the .mp4 file directly from drive with either quicktime or safari directly it does now play when it wouldn't before. When I download said video through the web gui it downloads a .TS version that also does not play in Safari or quicktime.

**Comment by wehbs** [comment]
Yes, here you go:

https://tempcloud.cf/

file name: firescrew_sample
number: 420

**Comment by wehbs** [comment]
sorry that seems broken, will try elsewhere

**Comment by chiefMarlin** [comment]
You can try
https://transfer.sh

**Comment by wehbs** [comment]
https://send-anywhere.com/

345270

**Comment by chiefMarlin** [comment]
> https://send-anywhere.com/
> 
> 345270

Im getting
The key is invalid or has expired

**Comment by wehbs** [comment]
New revelation, it does work on mobile safari.. lol.. Which is really what matters the most in this scenario since it also still works very well in Chrome.

**Comment by chiefMarlin** [comment]
Thanks for that, i think the issue was the filename was being requested with .ts extension but later served with as mp4
i have fixed it (atleast on my safari 😄 ) 
https://github.com/8ff/firescrew/releases/download/onnx_test_release/firescrew.darwin.arm64

**Comment by chiefMarlin** [comment]
Let me know if i can close this
