### ISSUE TITLE
Closing out the modal while video is playing continues to play the video audio in the background

### ISSUE THREAD

**Issue by wehbs** [8ff/firescrew#9]
Not clear if the video is also still playing but just not in view. This happens on both Safari and Chrome, but seems like not an issue on mobile.

**Comment by chiefMarlin** [comment]
This issue is fixed in 55616226f10e7c25d9c668e9645f46a677aead44 commit
https://github.com/8ff/firescrew/releases/download/onnx_test_release/firescrew.darwin.arm64
